<?php

use app\helpers\DocHelper;use yii\bootstrap4\Tabs;
/* @var $this yii\web\View */
/* @var $items [] */

$this->title = 'Generated configuration';
$this->subTitle = 'Using hiqdev/composer-config-plugin';

?>

<?= DocHelper::doc('2-Configuration') ?>

<hr />

<p>
Here are the files generated by the plugin for this project:
</p>

<?php


echo Tabs::widget(['items' => $items]);

?>